name: 'Deploy_Infra_FX2'

on:
  push:
    branches: [ "main" ]
    
jobs:
  deploy:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "AWS_REGION"
      AWS_ACCESS_KEY: ${{ secret.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secret.AWS:SECRET_KEY }}    
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Terraform init
      run: Terraform init
      working-directory: ./FX2
    - name: Terraform validate
      run: Terraform validate
      working-directory: ./FX2
    - name: Terraform plan
      run: Terraform plan
      working-directory: ./FX2 

